const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const PORT = process.env.PORT || 3000;

// ========== MIDDLEWARE ==========
app.use(cors({
  origin: ['https://projectforgen.netlify.app', 'http://localhost:3000'],
  credentials: true
}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ========== ENVIRONMENT VARIABLES ==========
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://rfejuvethmxenitvkyjp.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || '';

// ========== SUPABASE CLIENT ==========
const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// ========== HELPER: Get or Create User ==========
async function getOrCreateUser(supabaseId, email, name) {
  let { data: user, error } = await supabaseAdmin
    .from('users')
    .select('*')
    .eq('supabase_id', supabaseId)
    .single();
  
  if (error && error.code !== 'PGRST116') {
    console.error('Error fetching user:', error);
  }
  
  if (user) {
    if (name && user.name !== name) {
      await supabaseAdmin
        .from('users')
        .update({ name, updated_at: new Date() })
        .eq('supabase_id', supabaseId);
    }
    return user;
  }
  
  const { data: newUser, error: createError } = await supabaseAdmin
    .from('users')
    .insert([{
      supabase_id: supabaseId,
      email: email,
      name: name || email.split('@')[0],
      plan: 'free',
      monthly_generations: 0,
      last_reset_date: new Date().toISOString()
    }])
    .select()
    .single();
  
  if (createError) {
    console.error('Error creating user:', createError);
    throw new Error('Failed to create user');
  }
  
  return newUser;
}

// ========== HELPER: Check and Reset Monthly Limit ==========
async function checkAndResetLimit(user) {
  const now = new Date();
  const lastReset = new Date(user.last_reset_date);
  
  if (now.getMonth() !== lastReset.getMonth() || now.getFullYear() !== lastReset.getFullYear()) {
    const { error } = await supabaseAdmin
      .from('users')
      .update({
        monthly_generations: 0,
        last_reset_date: now.toISOString()
      })
      .eq('id', user.id);
    
    if (!error) {
      user.monthly_generations = 0;
      user.last_reset_date = now.toISOString();
    }
  }
  return user;
}

// ========== HELPER: Check if User Can Generate ==========
async function canGenerate(supabaseId) {
  const { data: user, error } = await supabaseAdmin
    .from('users')
    .select('*')
    .eq('supabase_id', supabaseId)
    .single();
  
  if (error || !user) {
    return { allowed: false, message: 'User not found', user: null };
  }
  
  await checkAndResetLimit(user);
  
  if (user.plan === 'pro' || user.plan === 'lifetime') {
    return { allowed: true, user };
  }
  
  if (user.monthly_generations >= 500) {
    return { 
      allowed: false, 
      message: '❌ Free limit reached (500/month). Please upgrade to Pro for unlimited access.',
      user 
    };
  }
  
  return { allowed: true, user };
}

// ========== HELPER: Generate Fallback Output (No API Key) ==========
function generateFallbackOutput(prompt, platform) {
  const isExcel = platform.includes('Excel') || platform.includes('Sheets') || platform.includes('Spreadsheet');
  const isAccounting = platform.includes('Tally') || platform.includes('QuickBooks');
  
  if (isExcel || isAccounting) {
    return `Product,Category,Quantity,Price,Total,Region
AI Laptop,Electronics,25,1299,32475,North
Smart Desk,Furniture,18,599,10782,East
Wireless Mouse,Accessories,120,29,3480,South
USB Hub,Accessories,85,19,1615,West
Software License,Digital,50,199,9950,Central

📊 Generated for ${platform}
📝 Prompt: ${prompt}
💰 Total Revenue: $58,302
📈 Growth: +18% YoY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Project Forge AI • Forge Anything with AI`;
  }
  
  if (platform.includes('PowerPoint') || platform.includes('Slides')) {
    return `📽️ PRESENTATION OUTLINE for ${platform}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SLIDE 1: TITLE SLIDE
• Project Forge AI - Professional Generation
• Date: ${new Date().toLocaleDateString()}

SLIDE 2: EXECUTIVE SUMMARY
• AI-powered content generation
• 500+ monthly free limit
• Multiple platform support

SLIDE 3: KEY METRICS
• Revenue Growth: +18%
• Customer Satisfaction: 94%
• Processing Time: <3 seconds

SLIDE 4: RECOMMENDATIONS
• Upgrade to Pro for unlimited access
• Export to multiple formats
• Voice and file upload support

SLIDE 5: THANK YOU
• Questions & Discussion
• Contact: support@projectforge.ai

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Project Forge AI`;
  }
  
  return `📄 DOCUMENT GENERATED for ${platform}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROMPT: ${prompt}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
The analysis shows strong performance in Q2 2025 with revenue growth of 18% compared to previous quarter. Key drivers include new product launches and expanded market reach.

KEY FINDINGS
• Revenue: $2.3M (↑18%)
• Customer acquisition: +245 new clients
• Top performing region: North America
• Product leader: AI Workstation series

RECOMMENDATIONS
1. Increase marketing spend in emerging markets
2. Launch loyalty program for existing customers
3. Expand AI feature set based on user feedback

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✨ Generated by Project Forge AI
🤖 Powered by Gemini AI (Free)
📅 ${new Date().toLocaleString()}`;
}

// ========== HELPER: Generate using OpenRouter with Gemini Free Model ==========
async function generateWithOpenRouter(prompt, platform) {
  let systemPrompt = `You are Project Forge AI, an expert assistant that generates professional content for "${platform}".

RULES:
1. Generate content EXACTLY for ${platform} format
2. If Excel/Sheets: Return CSV format with headers and realistic data
3. If Word/Docs: Return professional document with headings and paragraphs
4. If PowerPoint/Slides: Return slide-by-slide outline with bullet points
5. If Tally/QuickBooks: Return accounting format with invoices/GST
6. Always include realistic numbers and categories
7. Keep response clear, structured, and professional
8. Hindi or English — jo user ne likha wahi use karo

OUTPUT FORMAT:
- Platform: ${platform}
- Clean, readable structure
- Ready to copy-paste or export`;

  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://projectforgen.netlify.app',
        'X-Title': 'Project Forge AI'
      },
      body: JSON.stringify({
        model: 'google/gemini-2.0-flash-exp:free',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: prompt }
        ],
        max_tokens: 2000,
        temperature: 0.7
      })
    });

    const data = await response.json();
    
    if (data.error) {
      console.error('OpenRouter API Error:', data.error);
      return null;
    }
    
    if (data.choices && data.choices[0] && data.choices[0].message) {
      return data.choices[0].message.content;
    }
    
    return null;
  } catch (error) {
    console.error('OpenRouter fetch error:', error.message);
    return null;
  }
}

// ========== API ROUTES ==========

app.get('/api/health', (req, res) => {
  res.json({
    status: 'OK',
    timestamp: new Date().toISOString(),
    openrouter: OPENROUTER_API_KEY ? 'Configured ✅' : 'Not configured ⚠️'
  });
});

app.get('/', (req, res) => {
  res.send('🚀 Project Forge AI Backend is running!');
});

app.post('/api/user/sync', async (req, res) => {
  try {
    const { user_id, email, name } = req.body;
    
    if (!user_id || !email) {
      return res.status(400).json({ error: 'user_id and email required' });
    }
    
    const user = await getOrCreateUser(user_id, email, name);
    
    res.json({
      success: true,
      user: {
        id: user.id,
        supabaseId: user.supabase_id,
        email: user.email,
        name: user.name,
        plan: user.plan,
        monthlyGenerations: user.monthly_generations,
        remaining: user.plan === 'free' ? 500 - user.monthly_generations : 'Unlimited'
      }
    });
  } catch (error) {
    console.error('Sync error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.get('/api/user/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error } = await supabaseAdmin
      .from('users')
      .select('*')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (error || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    await checkAndResetLimit(user);
    
    res.json({
      id: user.id,
      supabaseId: user.supabase_id,
      email: user.email,
      name: user.name,
      plan: user.plan,
      monthlyGenerations: user.monthly_generations,
      remaining: user.plan === 'free' ? 500 - user.monthly_generations : 'Unlimited'
    });
  } catch (error) {
    console.error('Get user error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// MAIN GENERATION ENDPOINT
app.post('/api/generate', async (req, res) => {
  const startTime = Date.now();
  
  try {
    const { supabaseId, prompt, platform } = req.body;
    
    if (!supabaseId) {
      return res.status(401).json({ error: 'Please login first' });
    }
    
    if (!prompt || prompt.trim() === '') {
      return res.status(400).json({ error: 'Please enter a prompt' });
    }
    
    if (!platform) {
      return res.status(400).json({ error: 'Please select a platform' });
    }
    
    console.log(`📥 Generation request: User=${supabaseId}, Platform=${platform}, Prompt="${prompt.substring(0, 50)}..."`);
    
    const { allowed, message, user } = await canGenerate(supabaseId);
    if (!allowed) {
      return res.status(403).json({ error: message });
    }
    
    let output = null;
    let usedFallback = false;
    
    if (OPENROUTER_API_KEY && OPENROUTER_API_KEY !== '') {
      console.log('🤖 Calling OpenRouter with Gemini Free Model...');
      output = await generateWithOpenRouter(prompt, platform);
      
      if (output) {
        console.log('✅ Gemini success');
      } else {
        console.log('⚠️ Gemini failed, using fallback');
        output = generateFallbackOutput(prompt, platform);
        usedFallback = true;
      }
    } else {
      console.log('⚠️ No API key, using fallback mode');
      output = generateFallbackOutput(prompt, platform);
      usedFallback = true;
    }
    
    const { data: userData } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userData) {
      await supabaseAdmin
        .from('generation_history')
        .insert([{
          user_id: userData.id,
          prompt: prompt,
          platform: platform,
          output: output.substring(0, 10000),
          output_type: platform.includes('Excel') || platform.includes('Sheets') ? 'tabular' : 'doc'
        }]);
      
      if (user && user.plan === 'free') {
        await supabaseAdmin
          .from('users')
          .update({ monthly_generations: (user.monthly_generations || 0) + 1 })
          .eq('supabase_id', supabaseId);
      }
    }
    
    const duration = Date.now() - startTime;
    console.log(`✅ Generation complete in ${duration}ms (${usedFallback ? 'fallback' : 'Gemini'})`);
    
    res.json({
      success: true,
      output: output,
      usedFallback: usedFallback,
      duration: duration
    });
    
  } catch (error) {
    console.error('❌ Generation error:', error);
    res.status(500).json({ error: 'Something went wrong. Please try again.' });
  }
});

app.get('/api/history/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error: userError } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userError || !user) {
      return res.json([]);
    }
    
    const { data: history, error: historyError } = await supabaseAdmin
      .from('generation_history')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(100);
    
    if (historyError) {
      console.error('Get history error:', historyError);
      return res.json([]);
    }
    
    res.json(history || []);
  } catch (error) {
    console.error('Get history error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.delete('/api/history/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error: userError } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userError || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    await supabaseAdmin
      .from('generation_history')
      .delete()
      .eq('user_id', user.id);
    
    res.json({ success: true, message: 'History cleared' });
  } catch (error) {
    console.error('Clear history error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.post('/api/upgrade/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    const { plan } = req.body;
    
    if (!plan || !['pro', 'lifetime'].includes(plan)) {
      return res.status(400).json({ error: 'Invalid plan' });
    }
    
    const { error } = await supabaseAdmin
      .from('users')
      .update({ plan: plan })
      .eq('supabase_id', supabaseId);
    
    if (error) {
      return res.status(500).json({ error: 'Failed to upgrade' });
    }
    
    res.json({ success: true, plan: plan });
  } catch (error) {
    console.error('Upgrade error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

app.listen(PORT, () => {
  console.log(`
╔══════════════════════════════════════════════════╗
║     🚀 PROJECT FORGE AI BACKEND STARTED         ║
╠══════════════════════════════════════════════════╣
║  Port: ${PORT}                                      ║
║  Supabase: ${SUPABASE_URL.substring(0, 30)}...      ║
║  Model: Gemini 2.0 Flash (Free) ✅                ║
╚══════════════════════════════════════════════════╝
  `);
});