const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const PORT = process.env.PORT || 3000;
app.get("/", (req, res) => {
  res.send("Backend is running 🚀");
});

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ========== ENVIRONMENT VARIABLES ==========
const SUPABASE_URL = process.env.SUPABASE_URL || 'https://mpyhdklkgawyippnfwrs.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'sb_publishable_rmrmRUn5dxPioH3i3lSU0g_0KNkRmyL';
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || '';

// ========== Supabase Admin Client (for backend operations) ==========
const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
const supabaseAnon = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// ========== Helper Functions ==========

// Get or create user profile in Supabase 'users' table
async function getOrCreateUserProfile(supabaseId, email, name) {
  // Check if user profile exists
  const { data: existingUser, error: fetchError } = await supabaseAdmin
    .from('users')
    .select('*')
    .eq('supabase_id', supabaseId)
    .single();
  
  if (fetchError && fetchError.code !== 'PGRST116') {
    console.error('Error fetching user:', fetchError);
  }
  
  if (existingUser) {
    // Update name if changed
    if (name && existingUser.name !== name) {
      await supabaseAdmin
        .from('users')
        .update({ name, updated_at: new Date() })
        .eq('supabase_id', supabaseId);
      existingUser.name = name;
    }
    return existingUser;
  }
  
  // Create new user profile
  const { data: newUser, error: createError } = await supabaseAdmin
    .from('users')
    .insert([{
      supabase_id: supabaseId,
      email: email,
      name: name || email.split('@')[0],
      plan: 'free',
      monthly_generations: 0,
      last_reset_date: new Date().toISOString()
    }])
    .select()
    .single();
  
  if (createError) {
    console.error('Error creating user:', createError);
    throw new Error('Failed to create user profile');
  }
  
  return newUser;
}

// Reset monthly counter if needed
async function resetMonthlyCounterIfNeeded(user) {
  const now = new Date();
  const lastReset = new Date(user.last_reset_date);
  
  if (now.getMonth() !== lastReset.getMonth() || now.getFullYear() !== lastReset.getFullYear()) {
    const { error } = await supabaseAdmin
      .from('users')
      .update({
        monthly_generations: 0,
        last_reset_date: now.toISOString()
      })
      .eq('id', user.id);
    
    if (!error) {
      user.monthly_generations = 0;
      user.last_reset_date = now.toISOString();
    }
  }
  return user;
}

// Check if user can generate
async function canGenerate(supabaseId) {
  const { data: user, error } = await supabaseAdmin
    .from('users')
    .select('*')
    .eq('supabase_id', supabaseId)
    .single();
  
  if (error || !user) {
    return { allowed: false, message: 'User not found', user: null };
  }
  
  await resetMonthlyCounterIfNeeded(user);
  
  if (user.plan === 'pro' || user.plan === 'lifetime') {
    return { allowed: true, user };
  }
  
  if (user.monthly_generations >= 500) {
    return { allowed: false, message: 'Free limit reached (500/month). Please upgrade to Pro.', user };
  }
  
  return { allowed: true, user };
}

// Generate fallback output (when OpenRouter is not available)
function generateFallbackOutput(prompt, platform) {
  const isExcel = platform.includes('Excel') || platform.includes('Sheets') || platform.includes('Spreadsheet');
  const isAccounting = platform.includes('Tally') || platform.includes('QuickBooks');
  
  if (isExcel || isAccounting) {
    return `Product,Category,Quantity,Price,Total,Region
AI Laptop,Electronics,25,1299,32475,North
Smart Desk,Furniture,18,599,10782,East
Wireless Mouse,Accessories,120,29,3480,South
USB Hub,Accessories,85,19,1615,West
Software License,Digital,50,199,9950,Central

Generated for ${platform}
Prompt: ${prompt}
Total Revenue: $58,302
Growth: +18% YoY`;
  }
  
  return `📄 Document Generated for ${platform}

Prompt: ${prompt}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
The analysis shows strong performance in Q2 2025 with revenue growth of 18% compared to previous quarter. Key drivers include new product launches and expanded market reach.

KEY FINDINGS
• Revenue: $2.3M (↑18%)
• Customer acquisition: +245 new clients
• Top performing region: North America
• Product leader: AI Workstation series

RECOMMENDATIONS
1. Increase marketing spend in emerging markets
2. Launch loyalty program for existing customers
3. Expand AI feature set based on user feedback

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Project Forge AI
Powered by GPT-4/Claude/Gemini`;
}

// ========== API ROUTES ==========

// Health Check
app.get('/api/health', (req, res) => {
  res.json({
    status: 'OK',
    supabase: 'connected',
    timestamp: new Date().toISOString()
  });
});

// Sync user from Supabase Auth to 'users' table
app.post('/api/user/sync', async (req, res) => {
  try {
    const { supabaseId, email, name } = req.body;
    
    if (!supabaseId || !email) {
      return res.status(400).json({ error: 'supabaseId and email are required' });
    }
    
    const user = await getOrCreateUserProfile(supabaseId, email, name);
    
    res.json({
      success: true,
      user: {
        id: user.id,
        supabaseId: user.supabase_id,
        email: user.email,
        name: user.name,
        plan: user.plan,
        monthlyGenerations: user.monthly_generations,
        remainingGenerations: user.plan === 'free' ? 500 - user.monthly_generations : 'Unlimited'
      }
    });
  } catch (error) {
    console.error('Sync error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Get user details
app.get('/api/user/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error } = await supabaseAdmin
      .from('users')
      .select('*')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (error || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    await resetMonthlyCounterIfNeeded(user);
    
    // Get fresh user data after potential reset
    const { data: freshUser } = await supabaseAdmin
      .from('users')
      .select('*')
      .eq('supabase_id', supabaseId)
      .single();
    
    res.json({
      id: freshUser.id,
      supabaseId: freshUser.supabase_id,
      email: freshUser.email,
      name: freshUser.name,
      plan: freshUser.plan,
      monthlyGenerations: freshUser.monthly_generations,
      remainingGenerations: freshUser.plan === 'free' ? 500 - freshUser.monthly_generations : 'Unlimited'
    });
  } catch (error) {
    console.error('Get user error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Save generation history
app.post('/api/history', async (req, res) => {
  try {
    const { supabaseId, prompt, platform, output, outputType } = req.body;
    
    if (!supabaseId || !prompt || !platform || !output) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Get user ID from supabase_id
    const { data: user, error: userError } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userError || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    // Save to generation_history table
    const { data: history, error: historyError } = await supabaseAdmin
      .from('generation_history')
      .insert([{
        user_id: user.id,
        prompt: prompt,
        platform: platform,
        output: output,
        output_type: outputType || 'doc'
      }])
      .select()
      .single();
    
    if (historyError) {
      console.error('Save history error:', historyError);
      return res.status(500).json({ error: 'Failed to save history' });
    }
    
    // Increment monthly counter for free users
    const { data: userData } = await supabaseAdmin
      .from('users')
      .select('plan, monthly_generations')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userData && userData.plan === 'free') {
      await supabaseAdmin
        .from('users')
        .update({ monthly_generations: userData.monthly_generations + 1 })
        .eq('supabase_id', supabaseId);
    }
    
    res.json({ success: true, historyId: history.id });
  } catch (error) {
    console.error('Save history error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Get user history
app.get('/api/history/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error: userError } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userError || !user) {
      return res.json([]);
    }
    
    const { data: history, error: historyError } = await supabaseAdmin
      .from('generation_history')
      .select('*')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(100);
    
    if (historyError) {
      console.error('Get history error:', historyError);
      return res.json([]);
    }
    
    res.json(history);
  } catch (error) {
    console.error('Get history error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Clear user history
app.delete('/api/history/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    
    const { data: user, error: userError } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userError || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    const { error: deleteError } = await supabaseAdmin
      .from('generation_history')
      .delete()
      .eq('user_id', user.id);
    
    if (deleteError) {
      console.error('Clear history error:', deleteError);
      return res.status(500).json({ error: 'Failed to clear history' });
    }
    
    res.json({ success: true, message: 'History cleared' });
  } catch (error) {
    console.error('Clear history error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// AI Generate using OpenRouter API
app.post('/api/generate', async (req, res) => {
  try {
    const { supabaseId, prompt, platform } = req.body;
    
    if (!supabaseId || !prompt || !platform) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    
    // Check if user can generate
    const { allowed, message, user } = await canGenerate(supabaseId);
    if (!allowed) {
      return res.status(403).json({ error: message });
    }
    
    // Prepare system prompt based on platform
    let systemPrompt = `You are an AI assistant that generates professional content for ${platform}.`;
    
    if (platform.includes('Excel') || platform.includes('Sheets') || platform.includes('Spreadsheet')) {
      systemPrompt += ' Generate data in CSV format with headers. Include realistic numbers and categories. Return ONLY valid CSV data.';
    } else if (platform.includes('Word') || platform.includes('Docs') || platform.includes('Document')) {
      systemPrompt += ' Generate well-formatted document with headings, paragraphs, and bullet points.';
    } else if (platform.includes('PowerPoint') || platform.includes('Slides')) {
      systemPrompt += ' Generate presentation outline with slide titles and bullet points.';
    } else if (platform.includes('Tally') || platform.includes('QuickBooks')) {
      systemPrompt += ' Generate accounting data like invoices, ledgers, or GST reports in table format.';
    }
    
    let output = '';
    
    // If OpenRouter API key is available, use real AI
    if (OPENROUTER_API_KEY && OPENROUTER_API_KEY !== '') {
      try {
        const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
            'Content-Type': 'application/json',
            'HTTP-Referer': 'https://projectforautomation.netlify.app',
            'X-Title': 'Project Forge AI'
          },
          body: JSON.stringify({
            model: 'openai/gpt-3.5-turbo',
            messages: [
              { role: 'system', content: systemPrompt },
              { role: 'user', content: prompt }
            ],
            max_tokens: 2000,
            temperature: 0.7
          })
        });
        
        const data = await response.json();
        if (data.choices && data.choices[0] && data.choices[0].message) {
          output = data.choices[0].message.content;
        } else {
          throw new Error('Invalid API response');
        }
      } catch (apiError) {
        console.error('OpenRouter API error:', apiError);
        output = generateFallbackOutput(prompt, platform);
      }
    } else {
      // Fallback: Generate mock data (for demo when no API key)
      output = generateFallbackOutput(prompt, platform);
    }
    
    // Determine output type
    const outputType = (platform.includes('Excel') || platform.includes('Sheets')) ? 'tabular' : 'doc';
    
    // Auto-save to history
    const { data: userData } = await supabaseAdmin
      .from('users')
      .select('id')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (userData) {
      await supabaseAdmin
        .from('generation_history')
        .insert([{
          user_id: userData.id,
          prompt: prompt,
          platform: platform,
          output: output.substring(0, 5000),
          output_type: outputType
        }]);
      
      // Increment counter for free users
      if (user && user.plan === 'free') {
        await supabaseAdmin
          .from('users')
          .update({ monthly_generations: (user.monthly_generations || 0) + 1 })
          .eq('supabase_id', supabaseId);
      }
    }
    
    res.json({ output, outputType });
  } catch (error) {
    console.error('Generate error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Upgrade user plan (webhook or admin)
app.post('/api/upgrade/:supabaseId', async (req, res) => {
  try {
    const { supabaseId } = req.params;
    const { plan } = req.body;
    
    if (!plan || !['pro', 'lifetime'].includes(plan)) {
      return res.status(400).json({ error: 'Invalid plan' });
    }
    
    const { data: user, error } = await supabaseAdmin
      .from('users')
      .select('*')
      .eq('supabase_id', supabaseId)
      .single();
    
    if (error || !user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    await supabaseAdmin
      .from('users')
      .update({ plan: plan })
      .eq('supabase_id', supabaseId);
    
    res.json({ success: true, plan: plan });
  } catch (error) {
    console.error('Upgrade error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// ========== Start Server ==========
app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`📊 Supabase URL: ${SUPABASE_URL}`);
  console.log(`🤖 OpenRouter: ${OPENROUTER_API_KEY ? 'Configured' : 'Not configured (using fallback)'}`);
});
